from setuptools import setup

setup(
    name='spotifytools',
    version='0.1.0',
    description='Spotify developer API wrapper for easy processing and caching of resources.',
    url='https://github.com/dzejkob1218/spotify-tools',
    author='dzejkob1218',
    author_email='dzejkob1218@gmail.com',
    license='MIT',
    packages=['spotifytools'],
    keywords='spotify api development',
    classifiers=[
        'Development Status :: 2 - Pre-Alpha',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
    ],
    install_requires=['async-timeout>=4.0.2',
                        'beautifulsoup4>=4.11.1',
                        'certifi>=2022.12.7',
                        'charset-normalizer>=3.0.1',
                        'fuzzywuzzy>=0.18.0',
                        'idna>=3.4',
                        'langcodes>=3.3.0',
                        'langdetect>=1.0.9',
                        'Levenshtein>=0.20.9',
                        'lyricsgenius>=3.0.1',
                        'python-dotenv>=0.21.1',
                        'python-Levenshtein>=0.20.9',
                        'rapidfuzz>=2.13.7',
                        'redis>=4.4.2',
                        'requests>=2.28.2',
                        'six>=1.16.0',
                        'soupsieve>=2.3.2',
                        'spotipy>=2.22.1',
                        'urllib3>=1.26.14',
                        'pytest>=7.2.1',
                      ],
)